import { useEffect, useState } from 'react'
import QRCode from 'qrcode'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { adminAuthEmail, menuImageBucket, restaurantName, restaurantSlug } from '../lib/restaurant-config'
import './Admin.css'

const nav = [['dashboard', '⌂', 'Overview'], ['menu', '◫', 'Menu'], ['categories', '☷', 'Categories'], ['qr', '▦', 'QR Codes'], ['settings', '⚙', 'Settings']]
const Field = ({ label, children }) => <label>{label}{children}</label>
const PageLoader = ({ label = 'Loading data' }) => <div className="page-loader"><div className="loader-orbit"><i /><i /><i /></div><strong>{label}</strong><span>Please wait a moment</span></div>
const notify = (message, tone = 'success') => window.dispatchEvent(new CustomEvent('admin-feedback', { detail: { message, tone } }))
function Feedback() { const [notice, setNotice] = useState(null); useEffect(() => { const show = (event) => { setNotice(event.detail); window.setTimeout(() => setNotice(null), 3200) }; window.addEventListener('admin-feedback', show); return () => window.removeEventListener('admin-feedback', show) }, []); return notice && <div className={`admin-toast ${notice.tone}`} role="status">{notice.tone === 'success' ? '✓' : '!' } <span>{notice.message}</span></div> }

const loginLockKey = `palatotable-admin-lock:${restaurantSlug}`
const getLoginLock = () => { try { const value = JSON.parse(localStorage.getItem(loginLockKey) || 'null'); return value?.lockedUntil > Date.now() ? value : null } catch { return null } }

function Login() {
  const navigate = useNavigate(); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [lock, setLock] = useState(getLoginLock); const [now, setNow] = useState(() => Date.now())
  useEffect(() => { const timer = window.setInterval(() => { setNow(Date.now()); const activeLock = getLoginLock(); setLock(activeLock); if (!activeLock) localStorage.removeItem(loginLockKey) }, 1000); return () => window.clearInterval(timer) }, [])
  const submit = async (e) => { e.preventDefault(); const activeLock = getLoginLock(); if (activeLock) { setLock(activeLock); return } if (!supabase) return setError('Add Supabase environment variables first.'); setLoading(true); const { error: authError } = await supabase.auth.signInWithPassword({ email: adminAuthEmail, password }); if (authError) { const previous = (() => { try { return JSON.parse(localStorage.getItem(loginLockKey) || 'null') } catch { return null } })(); const attempts = (previous?.attempts || 0) + 1; if (attempts >= 3) { const nextLock = { attempts, lockedUntil: Date.now() + 60 * 60 * 1000 }; localStorage.setItem(loginLockKey, JSON.stringify(nextLock)); setLock(nextLock); setError('This device is locked for one hour after three failed attempts.') } else { localStorage.setItem(loginLockKey, JSON.stringify({ attempts })); setError(`Incorrect password. ${3 - attempts} attempt${3 - attempts === 1 ? '' : 's'} remaining.`) } setPassword(''); setLoading(false) } else { localStorage.removeItem(loginLockKey); navigate('/admin') } }
  const secondsLeft = lock ? Math.max(0, Math.ceil((lock.lockedUntil - now) / 1000)) : 0; const lockTime = `${String(Math.floor(secondsLeft / 60)).padStart(2, '0')}:${String(secondsLeft % 60).padStart(2, '0')}`
  return <main className="login-page"><section className="login-visual"><Link className="login-brand" to="/scan"><span>P</span>PalatoTable</Link><div><span className="login-kicker">RESTAURANT COMMAND CENTER</span><h1>Your menu.<br /><em>Managed simply.</em></h1><p>A focused workspace for your menu, table QR codes, and restaurant details.</p></div></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit} autoComplete="off"><div className="login-mobile-brand"><span>P</span><strong>PalatoTable</strong></div><span className="eyebrow">STAFF PORTAL</span><h2>{lock ? 'Access paused' : 'Welcome back'}</h2><p>{lock ? `Try again when the device lock ends in ${lockTime}.` : 'Sign in to manage DayNight Landikotal Bazar.'}</p><Field label="Admin email"><input type="email" name="staff-email" value={adminAuthEmail} readOnly aria-readonly="true" /></Field><Field label="Password"><input required disabled={Boolean(lock)} type="password" name="staff-password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} /></Field>{(error || lock) && <div className="login-error">{lock ? `Too many failed attempts. This device is locked for ${lockTime}.` : error}</div>}<button className="admin-primary login-submit" disabled={loading || Boolean(lock)}>{loading ? 'Signing in…' : lock ? `Try again in ${lockTime}` : 'Sign in securely'}</button><small>Three incorrect passwords lock this browser for one hour.</small></form></section></main>
}

function useData(table, restaurantId, order = 'display_order') {
  const [data, setData] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const reload = async () => { if (!restaurantId) return; setLoading(true); const result = await supabase.from(table).select('*').eq('restaurant_id', restaurantId).order(order, { ascending: order === 'display_order' }); if (result.error) setError(result.error.message); else setData(result.data || []); setLoading(false) }
  useEffect(() => { if (!restaurantId) return; supabase.from(table).select('*').eq('restaurant_id', restaurantId).order(order, { ascending: order === 'display_order' }).then((result) => { if (result.error) setError(result.error.message); else setData(result.data || []); setLoading(false) }) }, [restaurantId, table, order])
  return { data, error, loading, reload }
}

function Dashboard({ restaurantId, openPage }) {
  const { data: menu, loading: menuLoading } = useData('menu_items', restaurantId); const { data: categories, loading: categoryLoading } = useData('categories', restaurantId); const { data: tables, loading: tableLoading } = useData('qr_tokens', restaurantId, 'created_at')
  if (menuLoading || categoryLoading || tableLoading) return <PageLoader label="Loading dashboard" />
  const stats = [['Tables', tables.length, '▦', 'qr'], ['Menu items', menu.length, '◫', 'menu'], ['Categories', categories.length, '☷', 'categories']]
  return <><Header kicker="DAYNIGHT WORKSPACE" title="Good to see you" /><section className="admin-welcome"><div><span>YOUR RESTAURANT IS READY</span><strong>Keep your menu accurate and your table QR codes ready for guests.</strong></div><button onClick={() => openPage('qr')}>Manage table QRs <span>→</span></button></section><div className="stats-grid">{stats.map(([label, value, icon, page]) => <button className="stat-card" key={label} onClick={() => openPage(page)}><div className="stat-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>Manage {label.toLowerCase()} →</small></button>)}</div><section className="quick-actions"><div><span className="admin-kicker">QUICK ACTIONS</span><h2>What do you need to do?</h2></div><button onClick={() => openPage('menu')}><b>＋</b><span><strong>Add a food item</strong><small>Add a dish, price, photo and category</small></span></button><button onClick={() => openPage('categories')}><b>☷</b><span><strong>Organize categories</strong><small>Keep your digital menu easy to browse</small></span></button></section></>
}

function Categories({ restaurantId }) {
  const { data, error, loading, reload } = useData('categories', restaurantId); const { data: menuItems, loading: menuLoading } = useData('menu_items', restaurantId); const [editing, setEditing] = useState(null); const save = async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const record = { restaurant_id: restaurantId, name: f.get('name').trim(), display_order: editing?.display_order ?? data.length, is_active: true }; const result = editing?.id ? await supabase.from('categories').update(record).eq('id', editing.id) : await supabase.from('categories').insert(record); if (result.error) return alert(result.error.message); setEditing(null); reload() }
  const remove = async (row) => { if (confirm(`Delete ${row.name}?`)) { const { error: deleteError } = await supabase.from('categories').delete().eq('id', row.id); if (deleteError) alert(deleteError.message); else reload() } }
  if (loading || menuLoading) return <PageLoader label="Loading categories" />
    return <><Header kicker={`${data.length} CATEGORIES`} title="Category management" action="Add category" onAction={() => setEditing({ name: '' })} />{error && <div className="login-error">{error}</div>}<div className="category-admin-list">{data.map((row) => <article className="category-admin-row" key={row.id}><div><strong>{row.name}</strong><small>{menuItems.filter((item) => item.category_id === row.id).length} item(s)</small></div><div><button className="admin-secondary" onClick={() => setEditing(row)}>Edit</button><button className="danger-button" onClick={() => remove(row)}>Delete</button></div></article>)}</div>{editing && <Modal title={editing.id ? 'Edit category' : 'Add category'} close={() => setEditing(null)}><form onSubmit={save} className="admin-form-grid"><Field label="Category name"><input name="name" required defaultValue={editing.name} placeholder="e.g. Burgers" /></Field><button className="admin-primary">Save category</button></form></Modal>}</>
}

function MenuItemForm({ editing, categories, onSave }) {
  const initialImages = editing?.image_urls?.length ? editing.image_urls : editing?.image_url ? [editing.image_url] : []
  const [images, setImages] = useState(() => initialImages.map((url) => ({ id: crypto.randomUUID(), type: 'url', url, preview: url })))
  const [imageLink, setImageLink] = useState('')
  const addFiles = (event) => { const files = Array.from(event.target.files || []); const tooLarge = files.find((file) => file.size > 5242880); if (tooLarge) return notify('Each image must be 5 MB or smaller.', 'error'); setImages((current) => [...current, ...files.map((file) => ({ id: crypto.randomUUID(), type: 'file', file, preview: URL.createObjectURL(file) }))]); event.target.value = '' }
  const addLink = () => { const url = imageLink.trim(); if (!url) return; try { new URL(url) } catch { notify('Enter a complete public image URL.', 'error'); return } setImages((current) => [...current, { id: crypto.randomUUID(), type: 'url', url, preview: url }]); setImageLink('') }
  return <form onSubmit={(event) => { event.preventDefault(); onSave(new FormData(event.currentTarget), images) }} className="admin-form-grid"><Field label="Item name"><input name="name" required defaultValue={editing.name || ''} /></Field><Field label="Category"><select name="category" defaultValue={editing.category_id || ''}><option value="">No category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Price"><input name="price" type="number" min="0" required defaultValue={editing.price || ''} /></Field><Field label="Available"><input name="available" type="checkbox" defaultChecked={editing.is_available ?? true} /></Field><Field label="Description"><textarea name="description" defaultValue={editing.description || ''} placeholder="Describe this dish" /></Field><section className="image-manager"><div className="image-manager-head"><div><strong>Product images</strong><small>Add photos from your device or public image links.</small></div><span>{images.length} image{images.length === 1 ? '' : 's'}</span></div><div className="image-actions"><label className="image-upload-button">↑ Upload images<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={addFiles} /></label><div className="image-link-add"><input value={imageLink} onChange={(event) => setImageLink(event.target.value)} placeholder="Paste image URL" /><button type="button" onClick={addLink}>Add link</button></div></div>{images.length > 0 && <div className="image-preview-grid">{images.map((image, index) => <article key={image.id}><img src={image.preview} alt="" decoding="async" /><span>{index === 0 ? 'Cover image' : `Image ${index + 1}`}</span><button type="button" onClick={() => setImages((current) => current.filter((item) => item.id !== image.id))} aria-label="Remove image">×</button></article>)}</div>}</section><button className="admin-primary">{editing.id ? 'Save changes' : 'Add menu item'}</button></form>
}

function Menu({ restaurantId }) {
  const { data: items, error, loading, reload } = useData('menu_items', restaurantId); const { data: categories, loading: categoriesLoading } = useData('categories', restaurantId); const [editing, setEditing] = useState(null); const [query, setQuery] = useState(''); const [categoryFilter, setCategoryFilter] = useState(''); const [minPrice, setMinPrice] = useState(''); const [maxPrice, setMaxPrice] = useState(''); const [availability, setAvailability] = useState('all'); const [filtersOpen, setFiltersOpen] = useState(false)
  const save = async (formData, images) => { const files = images.filter((image) => image.type === 'file').map((image) => image.file); const linkedImages = images.filter((image) => image.type === 'url').map((image) => image.url); const uploadedImages = []; for (const file of files) { const path = `${restaurantId}/${crypto.randomUUID()}-${file.name.replaceAll(' ', '-')}`; const { error: uploadError } = await supabase.storage.from(menuImageBucket).upload(path, file, { upsert: false }); if (uploadError) return notify(uploadError.message, 'error'); uploadedImages.push(supabase.storage.from(menuImageBucket).getPublicUrl(path).data.publicUrl) } const imageUrls = [...linkedImages, ...uploadedImages]; const record = { restaurant_id: restaurantId, category_id: formData.get('category') || null, name: formData.get('name').trim(), description: formData.get('description').trim() || null, price: Number(formData.get('price')), image_url: imageUrls[0] || null, image_urls: imageUrls, is_available: formData.get('available') === 'on' }; const result = editing?.id ? await supabase.from('menu_items').update(record).eq('id', editing.id) : await supabase.from('menu_items').insert(record); if (result.error) return notify(result.error.message, 'error'); setEditing(null); reload(); notify(editing?.id ? 'Menu item updated.' : 'Menu item added.') }
  const toggle = async (row) => { const { error: updateError } = await supabase.from('menu_items').update({ is_available: !row.is_available }).eq('id', row.id); if (updateError) alert(updateError.message); else reload() }
  const remove = async (row) => { if (confirm(`Delete ${row.name}?`)) { const { error: deleteError } = await supabase.from('menu_items').delete().eq('id', row.id); if (deleteError) alert(deleteError.message); else reload() } }
  const visibleItems = items.filter((row) => (!categoryFilter || row.category_id === categoryFilter) && (!minPrice || Number(row.price) >= Number(minPrice)) && (!maxPrice || Number(row.price) <= Number(maxPrice)) && (availability === 'all' || (availability === 'available' && row.is_available) || (availability === 'sold-out' && !row.is_available)) && `${row.name} ${row.description || ''}`.toLowerCase().includes(query.toLowerCase()))
  const resetFilters = () => { setCategoryFilter(''); setMinPrice(''); setMaxPrice(''); setAvailability('all') }
  if (loading || categoriesLoading) return <PageLoader label="Loading menu" />
  return <><Header kicker={`${items.length} MENU ITEMS`} title="Menu management" action="Add item" onAction={() => setEditing({})} />{error && <div className="login-error">{error}</div>}<div className="content-toolbar"><label className="toolbar-search">⌕<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search food items" /></label><button className="admin-secondary" onClick={() => setFiltersOpen(true)}>☷ Filters</button></div><p className="result-summary">Showing {visibleItems.length} of {items.length} menu items</p>{filtersOpen && <div className="filter-backdrop" onClick={() => setFiltersOpen(false)}><aside className="filter-drawer" onClick={(e) => e.stopPropagation()}><header><div><span className="admin-kicker">MENU FILTERS</span><h2>Refine menu</h2></div><button onClick={() => setFiltersOpen(false)}>×</button></header><Field label="Category"><select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><div className="price-range"><Field label="Minimum price"><input value={minPrice} onChange={(e) => setMinPrice(e.target.value)} type="number" min="0" placeholder="0" /></Field><Field label="Maximum price"><input value={maxPrice} onChange={(e) => setMaxPrice(e.target.value)} type="number" min="0" placeholder="No limit" /></Field></div><Field label="Availability"><select value={availability} onChange={(e) => setAvailability(e.target.value)}><option value="all">All items</option><option value="available">Available</option><option value="sold-out">Sold out</option></select></Field><footer><button className="admin-secondary" onClick={resetFilters}>Reset</button><button className="admin-primary" onClick={() => setFiltersOpen(false)}>Apply filters</button></footer></aside></div>}<div className="admin-menu-grid">{visibleItems.map((row) => <article className={`admin-dish ${row.is_available ? '' : 'unavailable'}`} key={row.id}>{row.image_url && <img src={row.image_url} alt="" loading="lazy" decoding="async" />}<div><h3>{row.name}</h3><p>{row.description}</p><footer><strong>PKR {Number(row.price).toLocaleString()}</strong><button className={row.is_available ? 'toggle on' : 'toggle'} onClick={() => toggle(row)}><span />{row.is_available ? 'Available' : 'Sold out'}</button><button className="admin-secondary" onClick={() => setEditing(row)}>Edit</button><button className="admin-secondary" onClick={() => remove(row)}>Delete</button></footer></div></article>)}</div>{editing && <Modal title={editing.id ? 'Edit menu item' : 'Add menu item'} close={() => setEditing(null)}><MenuItemForm editing={editing} categories={categories} onSave={save} /></Modal>}</>
}


function QR({ restaurantId }) {
  const { data, loading, reload } = useData('qr_tokens', restaurantId, 'created_at'); const [table, setTable] = useState(''); const [expiry, setExpiry] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [createOpen, setCreateOpen] = useState(false)
  const create = async (e) => { e.preventDefault(); const { error } = await supabase.from('qr_tokens').insert({ restaurant_id: restaurantId, table_number: table.trim(), expires_at: expiry ? new Date(expiry).toISOString() : null }); if (error) return notify(`Could not create QR code: ${error.message}`, 'error'); setTable(''); setExpiry(''); setCreateOpen(false); reload(); notify('QR code created successfully.') }
  const now = new Date(); const isExpired = (row) => row.expires_at && new Date(row.expires_at) <= now; const visible = data.filter((row) => (status === 'all' || (status === 'active' ? row.is_active && !isExpired(row) : status === 'inactive' ? !row.is_active : isExpired(row))) && `${row.table_number} ${row.token}`.toLowerCase().includes(query.toLowerCase())); const activeCount = data.filter((row) => row.is_active && !isExpired(row)).length
  if (loading) return <PageLoader label="Loading table QR codes" />
  return <><Header kicker="TABLE ACCESS" title="QR code management" action="Create QR" onAction={() => setCreateOpen(true)} /><section className="qr-overview"><div><strong>{activeCount}</strong><span>Active QR codes</span></div><p>Each table QR is permanent unless you deactivate, delete, regenerate, or give it an expiry time.</p></section><div className="qr-toolbar"><label className="toolbar-search">⌕<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search table name or QR token" /></label><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All status</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="expired">Expired</option></select></div>{visible.length ? <div className="qr-grid">{visible.map((row) => <QRCard key={row.id} row={row} reload={reload} />)}</div> : <div className="empty-collection"><span>▦</span><h2>{data.length ? 'No QR codes match these filters' : 'Create your first table QR'}</h2><p>{data.length ? 'Try a different table name or status.' : 'Create one QR code per table, then download or print it.'}</p>{!data.length && <button className="admin-primary" onClick={() => setCreateOpen(true)}>Create table QR</button>}</div>}{createOpen && <Modal title="Create table QR" close={() => setCreateOpen(false)}><form className="admin-form-grid" onSubmit={create}><Field label="Table name"><input required value={table} onChange={(e) => setTable(e.target.value)} placeholder="e.g. Table 3" /></Field><Field label="QR expiry (optional)"><input value={expiry} onChange={(e) => setExpiry(e.target.value)} type="datetime-local" /><small>Leave blank to keep this QR permanent.</small></Field><button className="admin-primary">Generate QR code</button></form></Modal>}</>
}
function QRCard({ row, reload }) {
  const [url, setUrl] = useState(''); const link = `${location.origin}/scan/${row.token}`
  useEffect(() => { QRCode.toDataURL(link, { width: 360, margin: 2 }).then(setUrl) }, [link])
  const update = async (values, successMessage) => { const { error } = await supabase.from('qr_tokens').update(values).eq('id', row.id); if (error) notify(error.message, 'error'); else { reload(); notify(successMessage) } }
  const regenerate = () => { if (confirm(`Generate a new QR link for ${row.table_number}? The old QR will stop working.`)) update({ token: crypto.randomUUID().replaceAll('-', '') }, 'New QR link generated. The old link no longer works.') }
  const remove = () => { if (confirm(`Delete QR code for ${row.table_number}?`)) supabase.from('qr_tokens').delete().eq('id', row.id).then(({ error }) => { if (error) notify(error.message, 'error'); else { reload(); notify('QR code deleted.') } }) }
  const copy = async () => { try { await navigator.clipboard.writeText(link); notify('QR link copied to clipboard.') } catch { notify('Could not copy the QR link.', 'error') } }
  return <article className="qr-card"><header className="qr-card-head"><div><span className={row.is_active ? 'qr-state active' : 'qr-state'}>{row.is_active ? 'Active' : 'Inactive'}</span><h3>{row.table_number}</h3></div><button className="danger-button" onClick={remove}>Delete</button></header><div className="qr-preview">{url ? <img src={url} alt={`QR code for ${row.table_number}`} /> : <span className="qr-preview-loader" />}</div><div className="qr-token"><span>TABLE QR TOKEN</span><code title={row.token}>{row.token}</code></div><div className="qr-primary-action"><button onClick={copy}>⧉ Copy QR link</button></div><div className="qr-secondary-actions"><a href={url} download={`${row.table_number}-qr.png`}>↓ Download</a><button onClick={regenerate}>↻ Regenerate</button><button onClick={() => update({ is_active: !row.is_active }, row.is_active ? 'QR code deactivated.' : 'QR code activated.')}>{row.is_active ? 'Pause access' : 'Activate access'}</button></div></article>
}


function Header({ kicker, title, action, onAction }) { return <div className="admin-heading"><div><span className="admin-kicker">{kicker}</span><h1>{title}</h1></div>{action && <button className="admin-primary" onClick={onAction}>＋ {action}</button>}</div> }
function Modal({ title, close, children }) { return <div className="admin-modal-backdrop"><section className="admin-modal"><header><h2>{title}</h2><button onClick={close}>×</button></header>{children}</section></div> }

function Shell() {
  const navigate = useNavigate(); const [page, setPage] = useState('dashboard'); const [restaurant, setRestaurant] = useState(null); const [setupError, setSetupError] = useState('')
  useEffect(() => {
    let mounted = true
    const loadRestaurant = async () => {
      const { data: { user }, error: userError } = await supabase.auth.getUser()
      if (userError || !user) { await supabase.auth.signOut(); navigate('/admin/login', { replace: true }); return }
      const { data, error } = await supabase.from('restaurant_admins').select('restaurant_id, restaurants!inner(name, subdomain, owner_email, phone, contact_email)').eq('user_id', user.id).eq('is_active', true).eq('restaurants.subdomain', restaurantSlug).maybeSingle()
      if (!mounted) return
      if (error) { setSetupError(error.message); return }
      if (data) { setRestaurant({ id: data.restaurant_id, name: data.restaurants?.name || 'Restaurant', email: data.restaurants?.owner_email || '', phone: data.restaurants?.phone || '', contactEmail: data.restaurants?.contact_email || '' }); return }
      const { data: bootstrapped, error: bootstrapError } = await supabase.rpc('bootstrap_daynight_owner')
      if (!mounted) return
      if (bootstrapError) setSetupError('Restaurant setup is unavailable. Run the latest schema.sql once in Supabase SQL Editor.')
      else if (bootstrapped?.restaurant_id) setRestaurant({ id: bootstrapped.restaurant_id, name: restaurantName, email: adminAuthEmail, phone: '', contactEmail: '' })
      else setSetupError('The restaurant owner could not be created.')
    }
    loadRestaurant(); return () => { mounted = false }
  }, [navigate])
  if (setupError) return <main className="scan-error"><div className="brand-mark">P</div><h1>Admin setup incomplete</h1><p>{setupError}</p><button className="admin-primary" onClick={() => supabase.auth.signOut().then(() => navigate('/admin/login'))}>Log out</button></main>
  if (!restaurant) return <main className="scan-error"><span className="scan-spinner" /><p>Loading your restaurant…</p></main>
  const views = { dashboard: <Dashboard restaurantId={restaurant.id} openPage={setPage} />, menu: <Menu restaurantId={restaurant.id} />, categories: <Categories restaurantId={restaurant.id} />, qr: <QR restaurantId={restaurant.id} />, settings: <Settings restaurant={restaurant} /> }
  return <main className="admin-shell"><aside className="admin-sidebar"><Link className="admin-brand" to="/admin"><span>P</span><div><strong>PalatoTable</strong><small>{restaurant.name}</small></div></Link><nav>{nav.map(([id, icon, label]) => <button className={id === page ? 'active' : ''} key={id} onClick={() => setPage(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-footer"><div className="restaurant-chip"><span>{restaurant.name.slice(0, 2)}</span><div><strong>{restaurant.name}</strong><small>Administrator</small></div></div><button onClick={() => supabase.auth.signOut().then(() => navigate('/admin/login'))}>↪ Log out</button></div></aside><section className="admin-workspace"><header className="admin-topbar"><div className="mobile-admin-brand"><span>P</span><strong>PalatoTable</strong></div><span className="topbar-page">{nav.find(([id]) => id === page)?.[2]}</span><Link to="/scan">Open customer menu ↗</Link></header><div className="admin-content">{views[page]}</div><Feedback /></section></main>
}
function Settings({ restaurant }) {
  const [name, setName] = useState(restaurant.name); const [phone, setPhone] = useState(restaurant.phone); const [contactEmail, setContactEmail] = useState(restaurant.contactEmail); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState('')
  const saveProfile = async () => { const { error } = await supabase.from('restaurants').update({ name: name.trim(), phone: phone.trim() || null, contact_email: contactEmail.trim() || null }).eq('id', restaurant.id); if (error) notify(error.message, 'error'); else notify('Restaurant contact details saved.') }
  const changePassword = async (e) => { e.preventDefault(); if (password.length < 6) return notify('Use a password with at least 6 characters.', 'error'); if (password !== confirmPassword) return notify('Passwords do not match.', 'error'); const { error } = await supabase.auth.updateUser({ password }); if (error) notify(error.message, 'error'); else { setPassword(''); setConfirmPassword(''); notify('Password updated successfully.') } }
  return <><Header kicker="RESTAURANT PROFILE" title="Settings" /><section className="settings-hero"><span>PALATOTABLE · {restaurant.name}</span><p>Customer contact details appear in the menu settings screen.</p></section><div className="settings-grid"><article className="admin-card settings-form"><header><span className="settings-icon">⌁</span><div><h2>Customer contact</h2><p>Shown to guests when they need help.</p></div></header><Field label="Restaurant name"><input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="Phone number"><input type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Add a phone number" /></Field><Field label="Customer contact email"><input type="email" value={contactEmail} onChange={(e) => setContactEmail(e.target.value)} placeholder="Add a customer contact email" /></Field><button className="admin-primary" onClick={saveProfile}>Save restaurant details</button></article><form className="admin-card settings-form" onSubmit={changePassword}><header><span className="settings-icon">⌑</span><div><h2>Account security</h2><p>Keep staff access private and secure.</p></div></header><Field label="Admin email"><input value={restaurant.email} disabled readOnly /></Field><Field label="New password"><input required type="password" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} /></Field><Field label="Confirm new password"><input required type="password" autoComplete="new-password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} /></Field><button className="admin-primary">Update password</button><aside className="security-note">After three failed password attempts, this browser is locked from signing in for one hour.</aside></form></div></> 
}
export default function AdminApp({ login = false }) { return login ? <Login /> : <Shell /> }
