import { useEffect, useState } from 'react'
import QRCode from 'qrcode'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import './Admin.css'

const nav = [['dashboard', '⌂', 'Overview'], ['menu', '◫', 'Menu'], ['categories', '☷', 'Categories'], ['offers', '✦', 'Offers'], ['qr', '▦', 'QR Codes'], ['live', '◉', 'Live status'], ['settings', '⚙', 'Settings']]
const Field = ({ label, children }) => <label>{label}{children}</label>

function Login() {
  const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (e) => { e.preventDefault(); if (!supabase) return setError('Add Supabase environment variables first.'); setLoading(true); const { error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) { setError(authError.message); setLoading(false) } else navigate('/admin') }
  return <main className="login-page"><section className="login-visual"><Link className="login-brand" to="/scan"><span>P</span>PalatoTabale</Link><div><span className="login-kicker">RESTAURANT COMMAND CENTER</span><h1>Your menu.<br /><em>Managed simply.</em></h1><p>Manage real menu data, tables, offers, and guest sessions.</p></div></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><span className="eyebrow">STAFF PORTAL</span><h2>Welcome back</h2><p>Sign in with your Supabase Auth account.</p><Field label="Email"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></Field><Field label="Password"><input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></Field>{error && <div className="login-error">{error}</div>}<button className="admin-primary login-submit" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button></form></section></main>
}

function useData(table, restaurantId, order = 'display_order') {
  const [data, setData] = useState([]); const [error, setError] = useState('')
  const reload = async () => { if (!restaurantId) return; const result = await supabase.from(table).select('*').eq('restaurant_id', restaurantId).order(order, { ascending: order === 'display_order' }); if (result.error) setError(result.error.message); else setData(result.data || []) }
  useEffect(() => { if (!restaurantId) return; supabase.from(table).select('*').eq('restaurant_id', restaurantId).order(order, { ascending: order === 'display_order' }).then((result) => { if (result.error) setError(result.error.message); else setData(result.data || []) }) }, [restaurantId, table, order])
  return { data, error, reload }
}

function Dashboard({ restaurantId }) {
  const { data: menu } = useData('menu_items', restaurantId); const { data: categories } = useData('categories', restaurantId); const { data: tables } = useData('qr_tokens', restaurantId, 'created_at'); const { data: scans } = useData('scan_logs', restaurantId, 'scanned_at')
  const today = new Date().toDateString(); const stats = [['Tables', tables.length, '▦'], ['Menu items', menu.length, '◫'], ['Categories', categories.length, '☷'], ['Today scans', scans.filter((row) => new Date(row.scanned_at).toDateString() === today).length, '↗']]
  return <><Header kicker="LIVE DATABASE" title="Restaurant overview" /><div className="stats-grid">{stats.map(([label, value, icon]) => <article className="stat-card" key={label}><div className="stat-icon">{icon}</div><span>{label}</span><strong>{value}</strong></article>)}</div><article className="admin-card activity-card"><div className="card-heading"><div><span>Recent</span><strong>Guest scans</strong></div></div><div className="activity-table">{scans.slice(0, 8).map((row) => <div className="activity-row" key={row.id}><strong>{row.table_number}</strong><span>{row.device_type || 'Unknown'}</span><span>{new Date(row.scanned_at).toLocaleString()}</span><i>Logged</i></div>)}</div></article></>
}

function Categories({ restaurantId }) {
  const { data, error, reload } = useData('categories', restaurantId); const [editing, setEditing] = useState(null); const save = async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const record = { restaurant_id: restaurantId, name: f.get('name').trim(), icon: f.get('icon').trim() || null, display_order: Number(f.get('order')), is_active: f.get('active') === 'on' }; const result = editing?.id ? await supabase.from('categories').update(record).eq('id', editing.id) : await supabase.from('categories').insert(record); if (result.error) return alert(result.error.message); setEditing(null); reload() }
  const remove = async (row) => { if (confirm(`Delete ${row.name}?`)) { const { error: deleteError } = await supabase.from('categories').delete().eq('id', row.id); if (deleteError) alert(deleteError.message); else reload() } }
  return <><Header kicker={`${data.length} CATEGORIES`} title="Category management" action="Add category" onAction={() => setEditing({ name: '', icon: '', display_order: data.length + 1, is_active: true })} />{error && <div className="login-error">{error}</div>}<div className="admin-menu-grid">{data.map((row) => <article className="admin-dish" key={row.id}><div><span className="admin-kicker">{row.is_active ? 'ACTIVE' : 'HIDDEN'}</span><h3>{row.icon} {row.name}</h3><p>Display position: {row.display_order}</p><footer><button className="admin-secondary" onClick={() => setEditing(row)}>Edit</button><button className="admin-secondary" onClick={() => remove(row)}>Delete</button></footer></div></article>)}</div>{editing && <Modal title={editing.id ? 'Edit category' : 'Add category'} close={() => setEditing(null)}><form onSubmit={save} className="admin-form-grid"><Field label="Name"><input name="name" required defaultValue={editing.name} /></Field><Field label="Icon"><input name="icon" defaultValue={editing.icon || ''} placeholder="🍽" /></Field><Field label="Display order"><input name="order" type="number" min="0" defaultValue={editing.display_order} /></Field><Field label="Visible to guests"><input name="active" type="checkbox" defaultChecked={editing.is_active} /></Field><button className="admin-primary">Save category</button></form></Modal>}</>
}

function Menu({ restaurantId }) {
  const { data: items, error, reload } = useData('menu_items', restaurantId); const { data: categories } = useData('categories', restaurantId); const [editing, setEditing] = useState(null)
  const save = async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const record = { restaurant_id: restaurantId, category_id: f.get('category') || null, name: f.get('name').trim(), description: f.get('description').trim() || null, price: Number(f.get('price')), image_url: f.get('image').trim() || null, is_available: f.get('available') === 'on' }; const result = editing?.id ? await supabase.from('menu_items').update(record).eq('id', editing.id) : await supabase.from('menu_items').insert(record); if (result.error) return alert(result.error.message); setEditing(null); reload() }
  const toggle = async (row) => { const { error: updateError } = await supabase.from('menu_items').update({ is_available: !row.is_available }).eq('id', row.id); if (updateError) alert(updateError.message); else reload() }
  const remove = async (row) => { if (confirm(`Delete ${row.name}?`)) { const { error: deleteError } = await supabase.from('menu_items').delete().eq('id', row.id); if (deleteError) alert(deleteError.message); else reload() } }
  return <><Header kicker={`${items.length} MENU ITEMS`} title="Menu management" action="Add item" onAction={() => setEditing({})} />{error && <div className="login-error">{error}</div>}<div className="admin-menu-grid">{items.map((row) => <article className={`admin-dish ${row.is_available ? '' : 'unavailable'}`} key={row.id}>{row.image_url && <img src={row.image_url} alt="" />}<div><h3>{row.name}</h3><p>{row.description}</p><footer><strong>PKR {Number(row.price).toLocaleString()}</strong><button className={row.is_available ? 'toggle on' : 'toggle'} onClick={() => toggle(row)}><span />{row.is_available ? 'Available' : 'Sold out'}</button><button className="admin-secondary" onClick={() => setEditing(row)}>Edit</button><button className="admin-secondary" onClick={() => remove(row)}>Delete</button></footer></div></article>)}</div>{editing && <Modal title={editing.id ? 'Edit menu item' : 'Add menu item'} close={() => setEditing(null)}><form onSubmit={save} className="admin-form-grid"><Field label="Item name"><input name="name" required defaultValue={editing.name} /></Field><Field label="Category"><select name="category" defaultValue={editing.category_id || ''}><option value="">No category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Price"><input name="price" type="number" min="0" required defaultValue={editing.price} /></Field><Field label="Image URL"><input name="image" type="url" defaultValue={editing.image_url || ''} /></Field><Field label="Description"><textarea name="description" defaultValue={editing.description || ''} /></Field><Field label="Available"><input name="available" type="checkbox" defaultChecked={editing.is_available ?? true} /></Field><button className="admin-primary">Save item</button></form></Modal>}</>
}

function Offers({ restaurantId }) {
  const { data, reload } = useData('menu_items', restaurantId); const [editing, setEditing] = useState(null); const save = async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const { error } = await supabase.from('menu_items').update({ is_offer: true, offer_price: Number(f.get('price')), offer_description: f.get('description') || null, offer_start_date: f.get('start') || null, offer_end_date: f.get('end') || null }).eq('id', editing.id); if (error) alert(error.message); else { setEditing(null); reload() } }
  return <><Header kicker="MENU ITEM DISCOUNTS" title="Special offers" /> <div className="offer-admin-grid">{data.map((row) => <article className="admin-offer" key={row.id}><div><h2>{row.name}</h2><p>{row.is_offer ? `Offer price: PKR ${row.offer_price}` : 'No active offer'}</p><button className="admin-secondary" onClick={() => setEditing(row)}>{row.is_offer ? 'Edit offer' : 'Create offer'}</button></div></article>)}</div>{editing && <Modal title={`Offer for ${editing.name}`} close={() => setEditing(null)}><form className="admin-form-grid" onSubmit={save}><Field label="Offer price"><input name="price" type="number" min="0" max={editing.price} required defaultValue={editing.offer_price || ''} /></Field><Field label="Description"><input name="description" defaultValue={editing.offer_description || ''} /></Field><Field label="Start"><input name="start" type="datetime-local" /></Field><Field label="End"><input name="end" type="datetime-local" /></Field><button className="admin-primary">Save offer</button></form></Modal>}</>
}

function QR({ restaurantId }) {
  const { data, reload } = useData('qr_tokens', restaurantId, 'created_at'); const [table, setTable] = useState(''); const create = async (e) => { e.preventDefault(); const { error } = await supabase.from('qr_tokens').insert({ restaurant_id: restaurantId, table_number: table.trim() }); if (error) alert(error.message); else { setTable(''); reload() } }
  return <><Header kicker={`${data.length} TABLES`} title="QR code management" /><form className="manage-toolbar" onSubmit={create}><label>Table name <input required value={table} onChange={(e) => setTable(e.target.value)} placeholder="Table 3" /></label><button className="admin-primary">Generate QR</button></form><div className="qr-grid">{data.map((row) => <QRCard key={row.id} row={row} reload={reload} />)}</div></>
}
function QRCard({ row, reload }) { const [url, setUrl] = useState(''); useEffect(() => { QRCode.toDataURL(`${location.origin}/scan/${row.token}`, { width: 360 }).then(setUrl) }, [row.token]); const toggle = async () => { const { error } = await supabase.from('qr_tokens').update({ is_active: !row.is_active }).eq('id', row.id); if (error) alert(error.message); else reload() }; return <article className="qr-card"><span className={row.is_active ? 'qr-state active' : 'qr-state'}>{row.is_active ? 'Active' : 'Inactive'}</span>{url && <img src={url} alt={`QR code for ${row.table_number}`} />}<h3>{row.table_number}</h3><p>{row.token}</p><div><a href={url} download={`${row.table_number}-qr.png`}>Download</a><button onClick={toggle}>{row.is_active ? 'Deactivate' : 'Activate'}</button></div></article> }

function Live({ restaurantId }) { const { data } = useData('scan_logs', restaurantId, 'scanned_at'); return <><Header kicker="REAL-TIME SCANS" title="Live status" /><article className="admin-card activity-card"><div className="activity-table"><div className="activity-head"><span>TABLE</span><span>DEVICE</span><span>SCANNED</span><span>STATUS</span></div>{data.map((row) => <div className="activity-row" key={row.id}><strong>{row.table_number}</strong><span>{row.device_type || 'Unknown'}</span><span>{new Date(row.scanned_at).toLocaleString()}</span><i>Logged</i></div>)}</div></article></> }
function Header({ kicker, title, action, onAction }) { return <div className="admin-heading"><div><span className="admin-kicker">{kicker}</span><h1>{title}</h1></div>{action && <button className="admin-primary" onClick={onAction}>＋ {action}</button>}</div> }
function Modal({ title, close, children }) { return <div className="admin-modal-backdrop"><section className="admin-modal"><header><h2>{title}</h2><button onClick={close}>×</button></header>{children}</section></div> }

function Shell() { const navigate = useNavigate(); const [page, setPage] = useState('dashboard'); const [restaurant, setRestaurant] = useState(null); useEffect(() => { supabase.auth.getUser().then(async ({ data: { user } }) => { if (!user) return navigate('/admin/login'); const { data } = await supabase.from('restaurant_admins').select('restaurant_id, restaurants(name)').eq('user_id', user.id).eq('is_active', true).single(); if (data) setRestaurant({ id: data.restaurant_id, name: data.restaurants?.name || 'Restaurant' }) }) }, [navigate]); if (!restaurant) return <main className="scan-error"><span className="scan-spinner" /><p>Loading your restaurant…</p></main>; const views = { dashboard: <Dashboard restaurantId={restaurant.id} />, menu: <Menu restaurantId={restaurant.id} />, categories: <Categories restaurantId={restaurant.id} />, offers: <Offers restaurantId={restaurant.id} />, qr: <QR restaurantId={restaurant.id} />, live: <Live restaurantId={restaurant.id} />, settings: <Settings restaurant={restaurant} /> }; return <main className="admin-shell"><aside className="admin-sidebar"><Link className="admin-brand" to="/admin"><span>P</span><div><strong>PalatoTabale</strong><small>RESTAURANT OS</small></div></Link><nav>{nav.map(([id, icon, label]) => <button className={id === page ? 'active' : ''} key={id} onClick={() => setPage(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-footer"><div className="restaurant-chip"><span>{restaurant.name.slice(0, 2)}</span><div><strong>{restaurant.name}</strong><small>Administrator</small></div></div><button onClick={() => supabase.auth.signOut().then(() => navigate('/admin/login'))}>Log out</button></div></aside><section className="admin-workspace"><header className="admin-topbar"><Link to="/scan">Customer QR access</Link></header><div className="admin-content">{views[page]}</div></section></main> }
function Settings({ restaurant }) { const [name, setName] = useState(restaurant.name); const save = async () => { const { error } = await supabase.from('restaurants').update({ name }).eq('id', restaurant.id); if (error) alert(error.message); else alert('Settings saved') }; return <><Header kicker="RESTAURANT PROFILE" title="Settings" /><article className="admin-card settings-form"><Field label="Restaurant name"><input value={name} onChange={(e) => setName(e.target.value)} /></Field><button className="admin-primary" onClick={save}>Save changes</button></article></> }
export default function AdminApp({ login = false }) { return login ? <Login /> : <Shell /> }
